// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdaulxbcksusojcbsucr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkYXVseGJja3N1c29qY2JzdWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTAxMDc3NzIsImV4cCI6MjEwNTY4Mzc3Mn0.DvTB8RM3IU5qr_gWqQK3P9FlRz66t7zPyWpqOoDA5rg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});